name: CI
on: push
  push:
    branches:
      - jdn-canary
jobs:
  build-test-and-deploy:
    name: Build test and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
          registry-url: https://registry.npmjs.org/
      - run: yarn
        name: Install
      - run: yarn bootstrap
        name: Bootstrap
      - run: yarn test
        name: Test
